// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base.proto

/*
Package usercmd is a generated protocol buffer package.

It is generated from these files:
	base.proto

It has these top-level messages:
	LoginC2SMsg
	LoginS2CMsg
	IntoRoomC2SMsg
	IntoRoomS2CMsg
*/
package usercmd

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserCmd int32

const (
	UserCmd_LoginReq    UserCmd = 0
	UserCmd_LoginRes    UserCmd = 1
	UserCmd_IntoRoomReq UserCmd = 2
	UserCmd_IntoRoomRes UserCmd = 3
	UserCmd_MaxCmdId    UserCmd = 4
)

var UserCmd_name = map[int32]string{
	0: "LoginReq",
	1: "LoginRes",
	2: "IntoRoomReq",
	3: "IntoRoomRes",
	4: "MaxCmdId",
}
var UserCmd_value = map[string]int32{
	"LoginReq":    0,
	"LoginRes":    1,
	"IntoRoomReq": 2,
	"IntoRoomRes": 3,
	"MaxCmdId":    4,
}

func (x UserCmd) String() string {
	return proto.EnumName(UserCmd_name, int32(x))
}
func (UserCmd) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type LoginC2SMsg struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *LoginC2SMsg) Reset()                    { *m = LoginC2SMsg{} }
func (m *LoginC2SMsg) String() string            { return proto.CompactTextString(m) }
func (*LoginC2SMsg) ProtoMessage()               {}
func (*LoginC2SMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginC2SMsg) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LoginS2CMsg struct {
	PlayerId uint32 `protobuf:"varint,1,opt,name=playerId" json:"playerId,omitempty"`
}

func (m *LoginS2CMsg) Reset()                    { *m = LoginS2CMsg{} }
func (m *LoginS2CMsg) String() string            { return proto.CompactTextString(m) }
func (*LoginS2CMsg) ProtoMessage()               {}
func (*LoginS2CMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginS2CMsg) GetPlayerId() uint32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

type IntoRoomC2SMsg struct {
}

func (m *IntoRoomC2SMsg) Reset()                    { *m = IntoRoomC2SMsg{} }
func (m *IntoRoomC2SMsg) String() string            { return proto.CompactTextString(m) }
func (*IntoRoomC2SMsg) ProtoMessage()               {}
func (*IntoRoomC2SMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type IntoRoomS2CMsg struct {
	RoomId uint32 `protobuf:"varint,1,opt,name=RoomId" json:"RoomId,omitempty"`
}

func (m *IntoRoomS2CMsg) Reset()                    { *m = IntoRoomS2CMsg{} }
func (m *IntoRoomS2CMsg) String() string            { return proto.CompactTextString(m) }
func (*IntoRoomS2CMsg) ProtoMessage()               {}
func (*IntoRoomS2CMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *IntoRoomS2CMsg) GetRoomId() uint32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginC2SMsg)(nil), "usercmd.LoginC2SMsg")
	proto.RegisterType((*LoginS2CMsg)(nil), "usercmd.LoginS2CMsg")
	proto.RegisterType((*IntoRoomC2SMsg)(nil), "usercmd.IntoRoomC2SMsg")
	proto.RegisterType((*IntoRoomS2CMsg)(nil), "usercmd.IntoRoomS2cMsg")
	proto.RegisterEnum("usercmd.UserCmd", UserCmd_name, UserCmd_value)
}

func init() { proto.RegisterFile("base.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4a, 0x2c, 0x4e,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x2d, 0x4e, 0x2d, 0x4a, 0xce, 0x4d, 0x51,
	0x52, 0xe4, 0xe2, 0xf6, 0xc9, 0x4f, 0xcf, 0xcc, 0x73, 0x36, 0x0a, 0xf6, 0x2d, 0x4e, 0x17, 0x12,
	0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95,
	0x34, 0xa1, 0x4a, 0x82, 0x8d, 0x9c, 0x41, 0x4a, 0xa4, 0xb8, 0x38, 0x0a, 0x72, 0x12, 0x2b, 0x53,
	0x8b, 0x3c, 0x53, 0xc0, 0xca, 0x78, 0x83, 0xe0, 0x7c, 0x25, 0x01, 0x2e, 0x3e, 0xcf, 0xbc, 0x92,
	0xfc, 0xa0, 0xfc, 0xfc, 0x5c, 0x88, 0x81, 0x4a, 0x1a, 0x08, 0x91, 0x60, 0xa3, 0x64, 0x90, 0x7e,
	0x31, 0x2e, 0x36, 0x10, 0x0f, 0xae, 0x1b, 0xca, 0xd3, 0x0a, 0xe5, 0x62, 0x0f, 0x2d, 0x4e, 0x2d,
	0x72, 0xce, 0x4d, 0x11, 0xe2, 0xe1, 0xe2, 0x00, 0xdb, 0x18, 0x94, 0x5a, 0x28, 0xc0, 0x80, 0xc4,
	0x2b, 0x16, 0x60, 0x14, 0xe2, 0xe7, 0xe2, 0x86, 0x19, 0x08, 0x92, 0x66, 0x42, 0x15, 0x28, 0x16,
	0x60, 0x06, 0xa9, 0xf7, 0x4d, 0xac, 0x70, 0xce, 0x4d, 0xf1, 0x4c, 0x11, 0x60, 0x49, 0x62, 0x03,
	0x7b, 0xd8, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x38, 0x05, 0xda, 0xdb, 0xfe, 0x00, 0x00, 0x00,
}
