// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base.proto

/*
Package usercmd is a generated protocol buffer package.

It is generated from these files:
	base.proto

It has these top-level messages:
	LoginC2SMsg
	LoginS2CMsg
	IntoRoomC2SMsg
	IntoRoomS2CMsg
	BattleEntity
	CreateAllBattleEntitiesS2CMsg
	TurnInfoS2CMsg
*/
package usercmd

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserCmd int32

const (
	UserCmd_LoginReq                UserCmd = 0
	UserCmd_LoginRes                UserCmd = 1
	UserCmd_IntoRoomReq             UserCmd = 2
	UserCmd_IntoRoomRes             UserCmd = 3
	UserCmd_CreateAllBattleEntities UserCmd = 4
	UserCmd_TurnInfo                UserCmd = 5
	UserCmd_MaxCmdId                UserCmd = 6
)

var UserCmd_name = map[int32]string{
	0: "LoginReq",
	1: "LoginRes",
	2: "IntoRoomReq",
	3: "IntoRoomRes",
	4: "CreateAllBattleEntities",
	5: "TurnInfo",
	6: "MaxCmdId",
}
var UserCmd_value = map[string]int32{
	"LoginReq":                0,
	"LoginRes":                1,
	"IntoRoomReq":             2,
	"IntoRoomRes":             3,
	"CreateAllBattleEntities": 4,
	"TurnInfo":                5,
	"MaxCmdId":                6,
}

func (x UserCmd) String() string {
	return proto.EnumName(UserCmd_name, int32(x))
}
func (UserCmd) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PosIndex int32

const (
	PosIndex_PosELeft   PosIndex = 0
	PosIndex_PosECenter PosIndex = 1
	PosIndex_PosERight  PosIndex = 2
	PosIndex_PosBLeft   PosIndex = 3
	PosIndex_PosBCenter PosIndex = 4
	PosIndex_PosBRight  PosIndex = 5
)

var PosIndex_name = map[int32]string{
	0: "PosELeft",
	1: "PosECenter",
	2: "PosERight",
	3: "PosBLeft",
	4: "PosBCenter",
	5: "PosBRight",
}
var PosIndex_value = map[string]int32{
	"PosELeft":   0,
	"PosECenter": 1,
	"PosERight":  2,
	"PosBLeft":   3,
	"PosBCenter": 4,
	"PosBRight":  5,
}

func (x PosIndex) String() string {
	return proto.EnumName(PosIndex_name, int32(x))
}
func (PosIndex) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type LoginC2SMsg struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *LoginC2SMsg) Reset()                    { *m = LoginC2SMsg{} }
func (m *LoginC2SMsg) String() string            { return proto.CompactTextString(m) }
func (*LoginC2SMsg) ProtoMessage()               {}
func (*LoginC2SMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginC2SMsg) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LoginS2CMsg struct {
	PlayerId uint32 `protobuf:"varint,1,opt,name=playerId" json:"playerId,omitempty"`
}

func (m *LoginS2CMsg) Reset()                    { *m = LoginS2CMsg{} }
func (m *LoginS2CMsg) String() string            { return proto.CompactTextString(m) }
func (*LoginS2CMsg) ProtoMessage()               {}
func (*LoginS2CMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginS2CMsg) GetPlayerId() uint32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

type IntoRoomC2SMsg struct {
}

func (m *IntoRoomC2SMsg) Reset()                    { *m = IntoRoomC2SMsg{} }
func (m *IntoRoomC2SMsg) String() string            { return proto.CompactTextString(m) }
func (*IntoRoomC2SMsg) ProtoMessage()               {}
func (*IntoRoomC2SMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type IntoRoomS2CMsg struct {
	RoomId uint32 `protobuf:"varint,1,opt,name=RoomId" json:"RoomId,omitempty"`
}

func (m *IntoRoomS2CMsg) Reset()                    { *m = IntoRoomS2CMsg{} }
func (m *IntoRoomS2CMsg) String() string            { return proto.CompactTextString(m) }
func (*IntoRoomS2CMsg) ProtoMessage()               {}
func (*IntoRoomS2CMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *IntoRoomS2CMsg) GetRoomId() uint32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

type BattleEntity struct {
	PosIndex       uint32 `protobuf:"varint,1,opt,name=PosIndex" json:"PosIndex,omitempty"`
	EntityType     uint32 `protobuf:"varint,2,opt,name=EntityType" json:"EntityType,omitempty"`
	Health         uint32 `protobuf:"varint,3,opt,name=Health" json:"Health,omitempty"`
	PhysicalAttack uint32 `protobuf:"varint,4,opt,name=PhysicalAttack" json:"PhysicalAttack,omitempty"`
	MagicAttack    uint32 `protobuf:"varint,5,opt,name=MagicAttack" json:"MagicAttack,omitempty"`
	PhysicalDefend uint32 `protobuf:"varint,6,opt,name=PhysicalDefend" json:"PhysicalDefend,omitempty"`
	MagicDefend    uint32 `protobuf:"varint,7,opt,name=MagicDefend" json:"MagicDefend,omitempty"`
	MoveSpeed      uint32 `protobuf:"varint,8,opt,name=MoveSpeed" json:"MoveSpeed,omitempty"`
}

func (m *BattleEntity) Reset()                    { *m = BattleEntity{} }
func (m *BattleEntity) String() string            { return proto.CompactTextString(m) }
func (*BattleEntity) ProtoMessage()               {}
func (*BattleEntity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *BattleEntity) GetPosIndex() uint32 {
	if m != nil {
		return m.PosIndex
	}
	return 0
}

func (m *BattleEntity) GetEntityType() uint32 {
	if m != nil {
		return m.EntityType
	}
	return 0
}

func (m *BattleEntity) GetHealth() uint32 {
	if m != nil {
		return m.Health
	}
	return 0
}

func (m *BattleEntity) GetPhysicalAttack() uint32 {
	if m != nil {
		return m.PhysicalAttack
	}
	return 0
}

func (m *BattleEntity) GetMagicAttack() uint32 {
	if m != nil {
		return m.MagicAttack
	}
	return 0
}

func (m *BattleEntity) GetPhysicalDefend() uint32 {
	if m != nil {
		return m.PhysicalDefend
	}
	return 0
}

func (m *BattleEntity) GetMagicDefend() uint32 {
	if m != nil {
		return m.MagicDefend
	}
	return 0
}

func (m *BattleEntity) GetMoveSpeed() uint32 {
	if m != nil {
		return m.MoveSpeed
	}
	return 0
}

type CreateAllBattleEntitiesS2CMsg struct {
	Entities []*BattleEntity `protobuf:"bytes,1,rep,name=entities" json:"entities,omitempty"`
}

func (m *CreateAllBattleEntitiesS2CMsg) Reset()                    { *m = CreateAllBattleEntitiesS2CMsg{} }
func (m *CreateAllBattleEntitiesS2CMsg) String() string            { return proto.CompactTextString(m) }
func (*CreateAllBattleEntitiesS2CMsg) ProtoMessage()               {}
func (*CreateAllBattleEntitiesS2CMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CreateAllBattleEntitiesS2CMsg) GetEntities() []*BattleEntity {
	if m != nil {
		return m.Entities
	}
	return nil
}

type TurnInfoS2CMsg struct {
	BigTurnIndex      uint32 `protobuf:"varint,1,opt,name=BigTurnIndex" json:"BigTurnIndex,omitempty"`
	SmallTurnIndex    uint32 `protobuf:"varint,2,opt,name=SmallTurnIndex" json:"SmallTurnIndex,omitempty"`
	CurEntityPosIndex uint32 `protobuf:"varint,3,opt,name=CurEntityPosIndex" json:"CurEntityPosIndex,omitempty"`
}

func (m *TurnInfoS2CMsg) Reset()                    { *m = TurnInfoS2CMsg{} }
func (m *TurnInfoS2CMsg) String() string            { return proto.CompactTextString(m) }
func (*TurnInfoS2CMsg) ProtoMessage()               {}
func (*TurnInfoS2CMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *TurnInfoS2CMsg) GetBigTurnIndex() uint32 {
	if m != nil {
		return m.BigTurnIndex
	}
	return 0
}

func (m *TurnInfoS2CMsg) GetSmallTurnIndex() uint32 {
	if m != nil {
		return m.SmallTurnIndex
	}
	return 0
}

func (m *TurnInfoS2CMsg) GetCurEntityPosIndex() uint32 {
	if m != nil {
		return m.CurEntityPosIndex
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginC2SMsg)(nil), "usercmd.LoginC2SMsg")
	proto.RegisterType((*LoginS2CMsg)(nil), "usercmd.LoginS2CMsg")
	proto.RegisterType((*IntoRoomC2SMsg)(nil), "usercmd.IntoRoomC2SMsg")
	proto.RegisterType((*IntoRoomS2CMsg)(nil), "usercmd.IntoRoomS2cMsg")
	proto.RegisterType((*BattleEntity)(nil), "usercmd.BattleEntity")
	proto.RegisterType((*CreateAllBattleEntitiesS2CMsg)(nil), "usercmd.CreateAllBattleEntitiesS2CMsg")
	proto.RegisterType((*TurnInfoS2CMsg)(nil), "usercmd.TurnInfoS2CMsg")
	proto.RegisterEnum("usercmd.UserCmd", UserCmd_name, UserCmd_value)
	proto.RegisterEnum("usercmd.PosIndex", PosIndex_name, PosIndex_value)
}

func init() { proto.RegisterFile("base.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 469 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xdd, 0x8e, 0xd3, 0x30,
	0x10, 0x85, 0x37, 0xfd, 0xef, 0xb4, 0x5b, 0x8c, 0x25, 0x20, 0xe2, 0x4f, 0x25, 0x17, 0xa8, 0xac,
	0x50, 0x25, 0xca, 0x13, 0x6c, 0xc2, 0x4a, 0x44, 0xda, 0x4a, 0x55, 0xb2, 0x3c, 0x80, 0x37, 0x99,
	0xa6, 0x11, 0x49, 0x5c, 0x62, 0x17, 0x6d, 0xef, 0xb8, 0xe6, 0x9a, 0x07, 0x46, 0x8e, 0xdd, 0x24,
	0x5d, 0xc4, 0x5d, 0xce, 0x99, 0xcf, 0x67, 0xe4, 0x19, 0x07, 0xe0, 0x9e, 0x09, 0x5c, 0xee, 0x4b,
	0x2e, 0x39, 0x1d, 0x1e, 0x04, 0x96, 0x51, 0x1e, 0x3b, 0xef, 0x60, 0x72, 0xcb, 0x93, 0xb4, 0xf0,
	0x56, 0xe1, 0x5a, 0x24, 0x94, 0x42, 0xaf, 0x60, 0x39, 0xda, 0xd6, 0xdc, 0x5a, 0x8c, 0x83, 0xea,
	0xdb, 0xf9, 0x60, 0x90, 0x70, 0xe5, 0x29, 0xe4, 0x25, 0x8c, 0xf6, 0x19, 0x3b, 0x62, 0xe9, 0xc7,
	0x15, 0x76, 0x19, 0xd4, 0xda, 0x21, 0x30, 0xf3, 0x0b, 0xc9, 0x03, 0xce, 0x73, 0x1d, 0xe8, 0x2c,
	0x1a, 0x27, 0x5c, 0x45, 0xea, 0xfc, 0x73, 0x18, 0x28, 0x55, 0x9f, 0x36, 0xca, 0xf9, 0xd3, 0x81,
	0xa9, 0xcb, 0xa4, 0xcc, 0xf0, 0xa6, 0x90, 0xa9, 0x3c, 0xaa, 0x46, 0x1b, 0x2e, 0xfc, 0x22, 0xc6,
	0x87, 0x53, 0xa3, 0x93, 0xa6, 0x6f, 0x01, 0x34, 0x75, 0x77, 0xdc, 0xa3, 0xdd, 0xa9, 0xaa, 0x2d,
	0x47, 0x35, 0xf9, 0x8a, 0x2c, 0x93, 0x3b, 0xbb, 0xab, 0x9b, 0x68, 0x45, 0xdf, 0xc3, 0x6c, 0xb3,
	0x3b, 0x8a, 0x34, 0x62, 0xd9, 0xb5, 0x94, 0x2c, 0xfa, 0x6e, 0xf7, 0xaa, 0xfa, 0x23, 0x97, 0xce,
	0x61, 0xb2, 0x66, 0x49, 0x1a, 0x19, 0xa8, 0x5f, 0x41, 0x6d, 0xab, 0x9d, 0xf4, 0x05, 0xb7, 0x58,
	0xc4, 0xf6, 0xe0, 0x3c, 0x49, 0xbb, 0x75, 0x92, 0x81, 0x86, 0xad, 0x24, 0x43, 0xbc, 0x86, 0xf1,
	0x9a, 0xff, 0xc4, 0x70, 0x8f, 0x18, 0xdb, 0xa3, 0xaa, 0xde, 0x18, 0x4e, 0x00, 0x6f, 0xbc, 0x12,
	0x99, 0xc4, 0xeb, 0x2c, 0x6b, 0x8d, 0x27, 0x45, 0x61, 0xf6, 0xf1, 0x09, 0x46, 0x68, 0x1c, 0xdb,
	0x9a, 0x77, 0x17, 0x93, 0xd5, 0xb3, 0xa5, 0xd9, 0xee, 0xb2, 0x3d, 0xcf, 0xa0, 0xc6, 0x9c, 0xdf,
	0x16, 0xcc, 0xee, 0x0e, 0x65, 0xe1, 0x17, 0x5b, 0x6e, 0x52, 0x1c, 0x98, 0xba, 0x69, 0xa2, 0xcd,
	0x66, 0xe0, 0x67, 0x9e, 0xba, 0x72, 0x98, 0xb3, 0x2c, 0x6b, 0x28, 0x3d, 0xf8, 0x47, 0x2e, 0xfd,
	0x08, 0x4f, 0xbd, 0x43, 0xa9, 0xbb, 0xd6, 0x1b, 0xd4, 0x7b, 0xf8, 0xb7, 0x70, 0xf5, 0xcb, 0x82,
	0xe1, 0x37, 0x81, 0xa5, 0x97, 0xc7, 0x74, 0x0a, 0xa3, 0xea, 0xa9, 0x05, 0xf8, 0x83, 0x5c, 0xb4,
	0x94, 0x20, 0x16, 0x7d, 0x02, 0x93, 0xd3, 0x4b, 0x52, 0xe5, 0xce, 0xb9, 0x21, 0x48, 0x97, 0xbe,
	0x82, 0x17, 0xff, 0x19, 0x15, 0xe9, 0xa9, 0xb0, 0xd3, 0x95, 0x49, 0x5f, 0xa9, 0x35, 0x7b, 0xf0,
	0xf2, 0xd8, 0x8f, 0xc9, 0xe0, 0x2a, 0x6e, 0x5e, 0x9a, 0xaa, 0x6c, 0xb8, 0xb8, 0xb9, 0xc5, 0xad,
	0x24, 0x17, 0x74, 0x06, 0xa0, 0x94, 0x87, 0x85, 0xc4, 0x92, 0x58, 0xf4, 0x12, 0xc6, 0x4a, 0x07,
	0x69, 0xb2, 0x93, 0xa4, 0x63, 0x60, 0xb7, 0x82, 0xbb, 0x06, 0x76, 0x0d, 0xdc, 0x33, 0xb0, 0xab,
	0xe1, 0xfe, 0xfd, 0xa0, 0xfa, 0xf5, 0x3e, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x67, 0x2c, 0x6e,
	0xc1, 0x88, 0x03, 0x00, 0x00,
}
